version: "3.9"
services:
  app1:
    build: ./
    ports:
      - "80:5000"
  db-server:
    image: "mysql:8"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: unless-stopped
    container_name: "db-server"